### ISSUE TITLE
Error from Server

### ISSUE THREAD

**Issue by barrys-sms** [ibm-watson-iot/iot-docs#14]
Hi guys, really appreciate you putting this together for us. When running the script however I've been getting this issue:
`
Waiting for MongoDB CE Stateful Set to initialize and start  \Error from server (NotFound): statefulsets.apps "mas-mongo-ce" not found
` 
Are you aware of a workaround? Probably a simple solution..

**Comment by terenceq** [comment]
Do any of the steps under Troubleshooting provide any insight?

https://github.com/ibm-watson-iot/iot-docs/blob/master/mongodb/README.md#troubleshooting

Or perhaps an issue obtaining a PVC? 

https://github.com/ibm-watson-iot/iot-docs/blob/master/mongodb/README.md#configuration-details
