### ISSUE TITLE
Additional information needed in Grafana setup 

### ISSUE THREAD

**Issue by sbudhira** [ibm-watson-iot/iot-docs#9]
https://github.com/ibm-watson-iot/iot-docs/tree/master/monitoring#3-grafana-setup

1. If the default image is version does not get installed. The version can be updated
in Grafana operator yaml.
For example: containerImage: 'quay.io/integreatly/grafana-operator:v3.9.0'
version:3.9.0

2. Set the storage class that is available in your env.

**Comment by whitfiea** [comment]
Now updated to use mas_devops ansible collection and grafna v4
